# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a705df17fa6dfd04451b877915c81a9a77edcf06c457c6731042c58dd19da3d92452aa10712188a5f17e68816f1070b8e7cb44c9d37862b9a55feda280853a

test:
  secret_key_base: 258cdc1de5d28aa438dcc10138834b7d5de0176302a32b25a81c0b5e62b9aa51775d906ba4e757a287c3839b5c366516dc1f504e82e3b16befa00422f9f34b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
